name: Generate File List

on:
  push:
    branches:
      - main

jobs:
  generate-files-list:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Git identity
      - name: Set up Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Debug: Check contents of Pages directory
      - name: Check contents of Pages directory
        run: |
          ls -al ./Pages

      # Generate the file list
      - name: Generate file list (somedir)
        run: |
          ls ./Pages/*.html > files-list.json
          cat files-list.json

      # Set up authentication for pushing changes
      - name: Set up authentication
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git remote set-url origin https://github.com/${{ github.repository }}

      # Commit and push the generated file list
      - name: Commit and push file list
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add files-list.json
          git commit -m "Update file list"
          git push https://github.com/${{ github.repository }} HEAD:main
